[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
# It is strongly suggested to use encrypted mnemonics to avoid putting
# seed phrases directly into TOML files.  To do so, run:
#
#     clarinet deployments encrypt
#
# Enter your seed phrase and a password, then paste the encrypted mnemonic here.
#
# Otherwise, use the mnemonic field below:
#
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
